require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'jastip' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  target 'jastipTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.0', '< 4.0'
end

target 'jastip-tvOS' do
  # Pods for jastip-tvOS

  target 'jastip-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
